### ISSUE TITLE
Can't install - failing junit tests

### ISSUE THREAD

**Issue by e-spaulding** [gidim/Babler#2]
Hi, I've been trying to install Babler on my Mac (Big Sur) today using Java 8 (adoptopenjdk-8) and I've been running into some issues. The first couple issues I was able to solve by by modifying pom.xml, so I will try to describe them here.

Issue one: I was getting an error that com.sun.org.apache.regexp.internal could not be found, so I added this to the pom.xml:
```
<dependency>
   <groupId>javax.xml.parsers</groupId>
   <artifactId>aixport</artifactId>
   <version>1.3.1</version>
</dependency>
```

Issue two: I was getting another build failure error that read "The forked VM terminated without saying properly goodbye. VM crash or System.exit called." Originally I was able to solve this by ensuring the plugin version was 2.22.0 in pom.xml:
```
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-surefire-plugin</artifactId>
  <version>2.22.0</version>
</plugin>
```

However, I'm getting a similar error again. It looks like some of the tests passed successfully but then some of them crashed. If anyone still monitors this repo, can they see something obvious sticking out in this that I'm not seeing? Is one of the "solutions" I used above code-breaking and I should start over from scratch and try something different?

```
Downloading Language Identifcation Model. 161.7MB From Columbia University
--2021-03-13 20:55:35--  http://www.cs.columbia.edu/~gm2597/completeModel3.gm
Resolving www.cs.columbia.edu (www.cs.columbia.edu)... 128.59.11.206
Connecting to www.cs.columbia.edu (www.cs.columbia.edu)|128.59.11.206|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 161736595 (154M)
Saving to: ‘src/main/resources/completeModel3.gm’

src/main/resources/complete 100%[========================================>] 154.24M  13.2MB/s    in 12s     

2021-03-13 20:55:47 (12.5 MB/s) - ‘src/main/resources/completeModel3.gm’ saved [161736595/161736595]

Installing Maven Dependencies and Building JAR
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------< edu.columbia:Babler >-------------------------
[INFO] Building Babler 1.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-install-plugin:2.4:install-file (default-cli) @ Babler ---
[INFO] Installing /Users/elizabeth/Code/Babler/lib/azure-bing-search-java-0.12.0.jar to /Users/elizabeth/.m2/repository/net/billylieurance/azuresearch/azure-bing-search-java/0.12.0/azure-bing-search-java-0.12.0.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.299 s
[INFO] Finished at: 2021-03-13T20:55:48-07:00
[INFO] ------------------------------------------------------------------------
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------< edu.columbia:Babler >-------------------------
[INFO] Building Babler 1.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-install-plugin:2.4:install-file (default-cli) @ Babler ---
[INFO] Installing /Users/elizabeth/Code/Babler/lib/diffbot-java-1.0-SNAPSHOT.jar to /Users/elizabeth/.m2/repository/diffbot/diffbot-java/1.0-SNAPSHOT/diffbot-java-1.0-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.290 s
[INFO] Finished at: 2021-03-13T20:55:50-07:00
[INFO] ------------------------------------------------------------------------
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------< edu.columbia:Babler >-------------------------
[INFO] Building Babler 1.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-install-plugin:2.4:install-file (default-cli) @ Babler ---
[INFO] Installing /Users/elizabeth/Code/Babler/lib/feed4j.jar to /Users/elizabeth/.m2/repository/feed4j/feed4j/1.0/feed4j-1.0.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.296 s
[INFO] Finished at: 2021-03-13T20:55:51-07:00
[INFO] ------------------------------------------------------------------------
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------< edu.columbia:Babler >-------------------------
[INFO] Building Babler 1.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ Babler ---
[INFO] Deleting /Users/elizabeth/Code/Babler/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ Babler ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 455 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ Babler ---
[INFO] Compiling 86 source files to /Users/elizabeth/Code/Babler/target/classes
[WARNING] /Users/elizabeth/Code/Babler/src/main/java/edu/columbia/main/language_id/LanguageDetector.java:[2,39] ExceptionConstants is internal proprietary API and may be removed in a future release
[WARNING] /Users/elizabeth/Code/Babler/src/main/java/edu/columbia/main/language_id/LanguageCode.java:[4,49] Code is internal proprietary API and may be removed in a future release
[WARNING] /Users/elizabeth/Code/Babler/src/main/java/edu/columbia/main/HTTPClient.java:[9,21] AgentConfigurationError is internal proprietary API and may be removed in a future release
[WARNING] /Users/elizabeth/Code/Babler/src/main/java/edu/columbia/main/HTTPClient.java:[37,8] AgentConfigurationError is internal proprietary API and may be removed in a future release
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ Babler ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 489 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ Babler ---
[INFO] Compiling 10 source files to /Users/elizabeth/Code/Babler/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ Babler ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestDAO
[INFO] Running TestConfigFromFile
[INFO] Running TestLogEntry
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.07 s - in TestLogEntry
[INFO] Running TestResources
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 s - in TestResources
[INFO] Running TestYouTube
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.145 s - in TestConfigFromFile
[INFO] Running TestTweets
log4j:WARN No appenders could be found for logger (edu.columbia.main.LanguageDataManager).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Mar 13, 2021 8:55:58 PM com.mongodb.diagnostics.logging.JULLogger log
INFO: Cluster created with settings {hosts=[127.0.0.1:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
Mar 13, 2021 8:55:58 PM com.mongodb.diagnostics.logging.JULLogger log
INFO: Cluster created with settings {hosts=[127.0.0.1:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
Mar 13, 2021 8:55:58 PM com.mongodb.diagnostics.logging.JULLogger log
INFO: Opened connection [connectionId{localValue:1, serverValue:23}] to 127.0.0.1:27017
Mar 13, 2021 8:55:58 PM com.mongodb.diagnostics.logging.JULLogger log
INFO: No server chosen by WritableServerSelector from cluster description ClusterDescription{type=UNKNOWN, connectionMode=SINGLE, serverDescriptions=[ServerDescription{address=127.0.0.1:27017, type=UNKNOWN, state=CONNECTING}]}. Waiting for 30000 ms before timing out
Mar 13, 2021 8:55:58 PM com.mongodb.diagnostics.logging.JULLogger log
INFO: Monitor thread successfully connected to server with description ServerDescription{address=127.0.0.1:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[4, 4, 3]}, minWireVersion=0, maxWireVersion=9, maxDocumentSize=16777216, roundTripTimeNanos=2363687}
Mar 13, 2021 8:55:58 PM com.mongodb.diagnostics.logging.JULLogger log
INFO: Opened connection [connectionId{localValue:1, serverValue:24}] to 127.0.0.1:27017
Mar 13, 2021 8:55:58 PM com.mongodb.diagnostics.logging.JULLogger log
INFO: Monitor thread successfully connected to server with description ServerDescription{address=127.0.0.1:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[4, 4, 3]}, minWireVersion=0, maxWireVersion=9, maxDocumentSize=16777216, roundTripTimeNanos=1334665}
Mar 13, 2021 8:55:58 PM com.mongodb.diagnostics.logging.JULLogger log
INFO: Opened connection [connectionId{localValue:2, serverValue:25}] to 127.0.0.1:27017
Mar 13, 2021 8:55:58 PM com.mongodb.diagnostics.logging.JULLogger log
INFO: Opened connection [connectionId{localValue:2, serverValue:26}] to 127.0.0.1:27017
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.219 s - in TestDAO
[INFO] Running TestLanguageManager
log4j:WARN No appenders could be found for logger (edu.columbia.main.LanguageDataManager).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.332 s - in TestTweets
[INFO] Running TestLanguageIdentifier
log4j:WARN No appenders could be found for logger (edu.columbia.main.language_id.LanguageDetector).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 52.609 s - in TestLanguageIdentifier
[INFO] Running TestBlogPosts
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.461 s - in TestBlogPosts
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 21, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:01 min
[INFO] Finished at: 2021-03-13T20:56:53-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project Babler: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/elizabeth/Code/Babler/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /Users/elizabeth/Code/Babler && /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/bin/java -Xmx1024m -XX:MaxPermSize=256m -jar /Users/elizabeth/Code/Babler/target/surefire/surefirebooter1443627390539250089.jar /Users/elizabeth/Code/Babler/target/surefire 2021-03-13T20-55-57_543-jvmRun3 surefire6142595789670943033tmp surefire_05121312598197826934tmp
[ERROR] Process Exit Code: 0
[ERROR] Crashed tests:
[ERROR] TestLanguageManager
[ERROR] ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /Users/elizabeth/Code/Babler && /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/bin/java -Xmx1024m -XX:MaxPermSize=256m -jar /Users/elizabeth/Code/Babler/target/surefire/surefirebooter6554868019466165932.jar /Users/elizabeth/Code/Babler/target/surefire 2021-03-13T20-55-57_543-jvmRun2 surefire7090970763162342445tmp surefire_1404471784188848706tmp
[ERROR] Process Exit Code: 0
[ERROR] Crashed tests:
[ERROR] TestYouTube
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /Users/elizabeth/Code/Babler && /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/bin/java -Xmx1024m -XX:MaxPermSize=256m -jar /Users/elizabeth/Code/Babler/target/surefire/surefirebooter1443627390539250089.jar /Users/elizabeth/Code/Babler/target/surefire 2021-03-13T20-55-57_543-jvmRun3 surefire6142595789670943033tmp surefire_05121312598197826934tmp
[ERROR] Process Exit Code: 0
[ERROR] Crashed tests:
[ERROR] TestLanguageManager
[ERROR] ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /Users/elizabeth/Code/Babler && /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/bin/java -Xmx1024m -XX:MaxPermSize=256m -jar /Users/elizabeth/Code/Babler/target/surefire/surefirebooter6554868019466165932.jar /Users/elizabeth/Code/Babler/target/surefire 2021-03-13T20-55-57_543-jvmRun2 surefire7090970763162342445tmp surefire_1404471784188848706tmp
[ERROR] Process Exit Code: 0
[ERROR] Crashed tests:
[ERROR] TestYouTube
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.awaitResultsDone(ForkStarter.java:510)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.runSuitesForkOnceMultiple(ForkStarter.java:382)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:297)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:246)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1183)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR] Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /Users/elizabeth/Code/Babler && /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/bin/java -Xmx1024m -XX:MaxPermSize=256m -jar /Users/elizabeth/Code/Babler/target/surefire/surefirebooter6554868019466165932.jar /Users/elizabeth/Code/Babler/target/surefire 2021-03-13T20-55-57_543-jvmRun2 surefire7090970763162342445tmp surefire_1404471784188848706tmp
[ERROR] Process Exit Code: 0
[ERROR] Crashed tests:
[ERROR] TestYouTube
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:669)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.access$600(ForkStarter.java:115)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter$1.call(ForkStarter.java:371)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter$1.call(ForkStarter.java:347)
[ERROR] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[ERROR] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[ERROR] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[ERROR] 	at java.lang.Thread.run(Thread.java:748)
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by e-spaulding** [comment]
I also can't get a successful build on Linux. I'm also using Java 8 (using java 8 instead of a later version on both OSes because of the sun.management error but I guess I'm still getting it anyway). Here's the logging information for the Linux error:

```
Downloading Language Identifcation Model. 161.7MB From Columbia University
--2021-03-14 14:51:47--  http://www.cs.columbia.edu/~gm2597/completeModel3.gm
Resolving www.cs.columbia.edu (www.cs.columbia.edu)... 128.59.11.206
Connecting to www.cs.columbia.edu (www.cs.columbia.edu)|128.59.11.206|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 161736595 (154M)
Saving to: ‘src/main/resources/completeModel3.gm’

src/main/resources/completeModel3.gm            100%[====================================================================================================>] 154.24M  10.6MB/s    in 13s     

2021-03-14 14:52:01 (11.5 MB/s) - ‘src/main/resources/completeModel3.gm’ saved [161736595/161736595]

Installing Maven Dependencies and Building JAR
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for edu.columbia:Babler:jar:1.0
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ line 164, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] ------------------------< edu.columbia:Babler >-------------------------
[INFO] Building Babler 1.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-install-plugin:2.4:install-file (default-cli) @ Babler ---
[INFO] Installing /home/elizabeth/Babler/lib/azure-bing-search-java-0.12.0.jar to /home/elizabeth/.m2/repository/net/billylieurance/azuresearch/azure-bing-search-java/0.12.0/azure-bing-search-java-0.12.0.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.401 s
[INFO] Finished at: 2021-03-14T14:52:04-06:00
[INFO] ------------------------------------------------------------------------
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for edu.columbia:Babler:jar:1.0
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ line 164, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] ------------------------< edu.columbia:Babler >-------------------------
[INFO] Building Babler 1.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-install-plugin:2.4:install-file (default-cli) @ Babler ---
[INFO] Installing /home/elizabeth/Babler/lib/diffbot-java-1.0-SNAPSHOT.jar to /home/elizabeth/.m2/repository/diffbot/diffbot-java/1.0-SNAPSHOT/diffbot-java-1.0-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.406 s
[INFO] Finished at: 2021-03-14T14:52:05-06:00
[INFO] ------------------------------------------------------------------------
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for edu.columbia:Babler:jar:1.0
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ line 164, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] ------------------------< edu.columbia:Babler >-------------------------
[INFO] Building Babler 1.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-install-plugin:2.4:install-file (default-cli) @ Babler ---
[INFO] Installing /home/elizabeth/Babler/lib/feed4j.jar to /home/elizabeth/.m2/repository/feed4j/feed4j/1.0/feed4j-1.0.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.398 s
[INFO] Finished at: 2021-03-14T14:52:07-06:00
[INFO] ------------------------------------------------------------------------
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for edu.columbia:Babler:jar:1.0
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ line 164, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] ------------------------< edu.columbia:Babler >-------------------------
[INFO] Building Babler 1.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ Babler ---
[INFO] Deleting /home/elizabeth/Babler/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ Babler ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 455 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ Babler ---
[INFO] Compiling 86 source files to /home/elizabeth/Babler/target/classes
[INFO] -------------------------------------------------------------
[WARNING] COMPILATION WARNING : 
[INFO] -------------------------------------------------------------
[WARNING] /home/elizabeth/Babler/src/main/java/edu/columbia/main/language_id/LanguageCode.java:[4,49] Code is internal proprietary API and may be removed in a future release
[INFO] 1 warning
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/elizabeth/Babler/src/main/java/edu/columbia/main/HTTPClient.java:[9,21] error: cannot find symbol
[ERROR]  package sun.management
/home/elizabeth/Babler/src/main/java/edu/columbia/main/HTTPClient.java:[37,8] error: cannot find symbol
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.296 s
[INFO] Finished at: 2021-03-14T14:52:10-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project Babler: Compilation failure: Compilation failure: 
[ERROR] /home/elizabeth/Babler/src/main/java/edu/columbia/main/HTTPClient.java:[9,21] error: cannot find symbol
[ERROR]  package sun.management
[ERROR] /home/elizabeth/Babler/src/main/java/edu/columbia/main/HTTPClient.java:[37,8] error: cannot find symbol
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

```
